import { Repository } from 'typeorm';
import { DriveItem, DriveShare } from './entities/drive-item.entity';
import { User } from '../users/entities/user.entity';
import { CreateFolderDto } from './dto/create-folder.dto';
import { AddFileDto } from './dto/add-file.dto';
import { UpdateItemDto } from './dto/update-item.dto';
import { ShareItemDto } from './dto/share-item.dto';
import { MoveItemDto } from './dto/move-item.dto';
export declare class DriveService {
    private readonly itemRepo;
    private readonly shareRepo;
    private readonly userRepo;
    constructor(itemRepo: Repository<DriveItem>, shareRepo: Repository<DriveShare>, userRepo: Repository<User>);
    listItems(userId: string, parentId?: string, trashed?: boolean): Promise<DriveItem[]>;
    listSharedWithMe(userId: string): Promise<{
        sharedPermission: import("./entities/drive-item.entity").DriveSharePermission;
        sharedBy: User;
        id: string;
        name: string;
        type: import("./entities/drive-item.entity").DriveItemType;
        mimeType: string | null;
        storageKey: string | null;
        size: number | null;
        parentId: string | null;
        parent: DriveItem | null;
        children: DriveItem[];
        ownerId: string;
        owner: User;
        isTrashed: boolean;
        trashedAt: Date | null;
        isStarred: boolean;
        color: string | null;
        description: string | null;
        shares: DriveShare[];
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    }[]>;
    listStarred(userId: string): Promise<DriveItem[]>;
    listTrashed(userId: string): Promise<DriveItem[]>;
    search(userId: string, query: string): Promise<DriveItem[]>;
    adminListAll(parentId?: string): Promise<DriveItem[]>;
    adminListUserFiles(userId: string): Promise<DriveItem[]>;
    adminListSharedWithUser(userId: string): Promise<{
        sharedPermission: import("./entities/drive-item.entity").DriveSharePermission;
        sharedBy: User;
        id: string;
        name: string;
        type: import("./entities/drive-item.entity").DriveItemType;
        mimeType: string | null;
        storageKey: string | null;
        size: number | null;
        parentId: string | null;
        parent: DriveItem | null;
        children: DriveItem[];
        ownerId: string;
        owner: User;
        isTrashed: boolean;
        trashedAt: Date | null;
        isStarred: boolean;
        color: string | null;
        description: string | null;
        shares: DriveShare[];
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    }[]>;
    getItem(id: string, userId: string, isAdmin?: boolean): Promise<DriveItem>;
    createFolder(userId: string, dto: CreateFolderDto): Promise<DriveItem>;
    addFile(userId: string, dto: AddFileDto): Promise<DriveItem>;
    updateItem(id: string, userId: string, dto: UpdateItemDto): Promise<DriveItem>;
    moveItem(id: string, userId: string, dto: MoveItemDto): Promise<DriveItem>;
    copyItem(id: string, userId: string, targetFolderId?: string): Promise<DriveItem>;
    private deepCopy;
    trashItem(id: string, userId: string): Promise<DriveItem>;
    restoreItem(id: string, userId: string): Promise<DriveItem>;
    permanentDelete(id: string, userId: string, isAdmin?: boolean): Promise<void>;
    private recursiveDelete;
    shareItem(id: string, ownerId: string, dto: ShareItemDto): Promise<DriveShare[]>;
    removeShare(itemId: string, shareId: string, userId: string): Promise<void>;
    listShares(itemId: string, userId: string): Promise<DriveShare[]>;
    searchUsers(query: string, excludeId: string): Promise<User[]>;
    getBreadcrumb(folderId: string, userId: string, isAdmin?: boolean): Promise<{
        id: string;
        name: string;
    }[]>;
    getStorageStats(userId: string): Promise<{
        usedBytes: number;
        totalFiles: number;
    }>;
    private assertOwnership;
    private assertFolderOwnership;
    private canAccess;
    private wouldCreateCycle;
    getDescendantFiles(folderId: string, userId: string, isAdmin?: boolean): Promise<DriveItem[]>;
    private collectFiles;
}
