import { Response } from 'express';
import { DriveService } from './drive.service';
import { ConfigService } from '@nestjs/config';
import { CreateFolderDto } from './dto/create-folder.dto';
import { AddFileDto } from './dto/add-file.dto';
import { UpdateItemDto } from './dto/update-item.dto';
import { ShareItemDto } from './dto/share-item.dto';
import { MoveItemDto } from './dto/move-item.dto';
export declare class DriveController {
    private readonly driveService;
    private readonly config;
    private readonly fileServerUrl;
    constructor(driveService: DriveService, config: ConfigService);
    listItems(req: any, parentId?: string, trashed?: string): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    listSharedWithMe(req: any): Promise<{
        sharedPermission: import("./entities/drive-item.entity").DriveSharePermission;
        sharedBy: import("../users/entities/user.entity").User;
        id: string;
        name: string;
        type: import("./entities/drive-item.entity").DriveItemType;
        mimeType: string | null;
        storageKey: string | null;
        size: number | null;
        parentId: string | null;
        parent: import("./entities/drive-item.entity").DriveItem | null;
        children: import("./entities/drive-item.entity").DriveItem[];
        ownerId: string;
        owner: import("../users/entities/user.entity").User;
        isTrashed: boolean;
        trashedAt: Date | null;
        isStarred: boolean;
        color: string | null;
        description: string | null;
        shares: import("./entities/drive-item.entity").DriveShare[];
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    }[]>;
    listStarred(req: any): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    listTrash(req: any): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    search(req: any, q: string): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    stats(req: any): Promise<{
        usedBytes: number;
        totalFiles: number;
    }>;
    searchUsers(req: any, q: string): Promise<import("../users/entities/user.entity").User[]>;
    adminListAll(parentId?: string): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    adminUserFiles(userId: string): Promise<import("./entities/drive-item.entity").DriveItem[]>;
    adminSharedWithUser(userId: string): Promise<{
        sharedPermission: import("./entities/drive-item.entity").DriveSharePermission;
        sharedBy: import("../users/entities/user.entity").User;
        id: string;
        name: string;
        type: import("./entities/drive-item.entity").DriveItemType;
        mimeType: string | null;
        storageKey: string | null;
        size: number | null;
        parentId: string | null;
        parent: import("./entities/drive-item.entity").DriveItem | null;
        children: import("./entities/drive-item.entity").DriveItem[];
        ownerId: string;
        owner: import("../users/entities/user.entity").User;
        isTrashed: boolean;
        trashedAt: Date | null;
        isStarred: boolean;
        color: string | null;
        description: string | null;
        shares: import("./entities/drive-item.entity").DriveShare[];
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    }[]>;
    proxyFile(key: string, res: Response): Response<any, Record<string, any>> | undefined;
    getItem(req: any, id: string): Promise<import("./entities/drive-item.entity").DriveItem>;
    getBreadcrumb(req: any, id: string): Promise<{
        id: string;
        name: string;
    }[]>;
    listShares(req: any, id: string): Promise<import("./entities/drive-item.entity").DriveShare[]>;
    createFolder(req: any, dto: CreateFolderDto): Promise<import("./entities/drive-item.entity").DriveItem>;
    addFile(req: any, dto: AddFileDto): Promise<import("./entities/drive-item.entity").DriveItem>;
    updateItem(req: any, id: string, dto: UpdateItemDto): Promise<import("./entities/drive-item.entity").DriveItem>;
    moveItem(req: any, id: string, dto: MoveItemDto): Promise<import("./entities/drive-item.entity").DriveItem>;
    copyItem(req: any, id: string, dto: MoveItemDto): Promise<import("./entities/drive-item.entity").DriveItem>;
    trashItem(req: any, id: string): Promise<import("./entities/drive-item.entity").DriveItem>;
    restoreItem(req: any, id: string): Promise<import("./entities/drive-item.entity").DriveItem>;
    permanentDelete(req: any, id: string): Promise<void>;
    shareItem(req: any, id: string, dto: ShareItemDto): Promise<import("./entities/drive-item.entity").DriveShare[]>;
    removeShare(req: any, id: string, shareId: string): Promise<void>;
    downloadZip(req: any, id: string, res: Response): Promise<void>;
}
