import { DataSource } from 'typeorm';

// All 416 sectors of Rwanda, keyed by district code.
const SECTORS: Record<string, string[]> = {
  // Kigali City
  'KIG-GAS': [
    'Bumbogo',
    'Gatsata',
    'Gikomero',
    'Gisozi',
    'Jabana',
    'Jali',
    'Kacyiru',
    'Kimihurura',
    'Kimironko',
    'Kinyinya',
    'Ndera',
    'Nduba',
    'Remera',
    'Rusororo',
    'Rutunga',
  ],
  'KIG-KIC': [
    'Gahanga',
    'Gatenga',
    'Gikondo',
    'Kagarama',
    'Kanombe',
    'Kicukiro',
    'Kigarama',
    'Masaka',
    'Niboye',
    'Nyarugunga',
  ],
  'KIG-NYA': [
    'Gitega',
    'Kanyinya',
    'Kigali',
    'Kimisagara',
    'Mageragere',
    'Muhima',
    'Nyakabanda',
    'Nyamirambo',
    'Nyarugenge',
    'Rwezamenyo',
  ],
  // Northern Province
  'NOR-BUR': [
    'Bungwe',
    'Butaro',
    'Cyanika',
    'Cyeru',
    'Gahunga',
    'Gatebe',
    'Gitovu',
    'Kagogo',
    'Kinoni',
    'Kinyababa',
    'Kivuye',
    'Nemba',
    'Rugarama',
    'Rugendabari',
    'Ruhunde',
    'Rusarabuye',
    'Rwerere',
  ],
  'NOR-GAK': [
    'Busengo',
    'Coko',
    'Cyabingo',
    'Gakenke',
    'Gashenyi',
    'Igisuni',
    'Kamubuga',
    'Karambo',
    'Kivuruga',
    'Mataba',
    'Minazi',
    'Mugunga',
    'Muhondo',
    'Muyongwe',
    'Muzo',
    'Nemba',
    'Ruli',
    'Rusasa',
    'Rushashi',
  ],
  'NOR-GIC': [
    'Bukure',
    'Bwisige',
    'Byumba',
    'Cyumba',
    'Giti',
    'Kageyo',
    'Kaniga',
    'Manyagiro',
    'Miyove',
    'Mukarange',
    'Muko',
    'Mutete',
    'Nyamiyaga',
    'Nyankenke',
    'Rubaya',
    'Rukomo',
    'Rushaki',
    'Rutare',
    'Ruvune',
    'Rwamiko',
    'Shangasha',
  ],
  'NOR-MUS': [
    'Busogo',
    'Cyuve',
    'Gacaca',
    'Gashaki',
    'Gataraga',
    'Kimonyi',
    'Kinigi',
    'Muhoza',
    'Muko',
    'Musanze',
    'Nkotsi',
    'Nyange',
    'Remera',
    'Rwaza',
    'Shingiro',
  ],
  'NOR-RUL': [
    'Base',
    'Burega',
    'Bushoki',
    'Buyoga',
    'Cyinzuzi',
    'Cyungo',
    'Kinihira',
    'Kisaro',
    'Masoro',
    'Mbogo',
    'Murambi',
    'Ngoma',
    'Ntarabana',
    'Rukozo',
    'Rusiga',
    'Shyorongi',
    'Tumba',
  ],
  // Southern Province
  'SOU-GIS': [
    'Gikonko',
    'Gishubi',
    'Kansi',
    'Kibilizi',
    'Kigembe',
    'Mamba',
    'Muganza',
    'Mugombwa',
    'Mukindo',
    'Musha',
    'Ndora',
    'Nyanza',
    'Save',
  ],
  'SOU-HUY': [
    'Gishamvu',
    'Huye',
    'Karama',
    'Kigoma',
    'Mukura',
    'Ngoma',
    'Ruhashya',
    'Rusatira',
    'Rwaniro',
    'Simbi',
    'Tumba',
  ],
  'SOU-KAM': [
    'Gacurabwenge',
    'Kamonyi',
    'Karama',
    'Kayenzi',
    'Kayumbu',
    'Mugina',
    'Musambira',
    'Ngamba',
    'Nyamiyaga',
    'Nyarubaka',
    'Rugarika',
    'Rukoma',
    'Runda',
  ],
  'SOU-MUH': [
    'Cyeza',
    'Kabacuzi',
    'Kibangu',
    'Kiyumba',
    'Muhanga',
    'Mushishiro',
    'Nyabinoni',
    'Nyamabuye',
    'Nyarusange',
    'Rongi',
    'Rugendabari',
    'Shyogwe',
  ],
  'SOU-MAG': [
    'Buruhukiro',
    'Cyanika',
    'Gasaka',
    'Gatare',
    'Kaduha',
    'Kamegeri',
    'Kibirizi',
    'Kibumbwe',
    'Kitabi',
    'Mbazi',
    'Mugano',
    'Musange',
    'Musebeya',
    'Mushubi',
    'Nkomane',
    'Tare',
    'Uwinkingi',
  ],
  'SOU-NYA': [
    'Busasamana',
    'Busoro',
    'Cyabakamyi',
    'Kibirizi',
    'Kigoma',
    'Mukingo',
    'Muyira',
    'Ntyazo',
    'Nyagisozi',
    'Rwabicuma',
  ],
  'SOU-RUG': [
    'Busanze',
    'Cyahinda',
    'Kibeho',
    'Kivu',
    'Mata',
    'Mugusa',
    'Munini',
    'Ngera',
    'Ngoma',
    'Nyabimata',
    'Nyagisozi',
    'Ruheru',
    'Ruramba',
    'Rusenge',
  ],
  'SOU-RUH': [
    'Bweramana',
    'Byimana',
    'Kabagari',
    'Kinazi',
    'Kinihira',
    'Mbuye',
    'Mwendo',
    'Ntongwe',
    'Ruhango',
  ],
  // Eastern Province
  'EAS-BUG': [
    'Gashora',
    'Juru',
    'Kamabuye',
    'Ntarama',
    'Nyamata',
    'Nyarugenge',
    'Rilima',
    'Ruhuha',
    'Rweru',
    'Shyara',
  ],
  'EAS-GAT': [
    'Gasange',
    'Gatsibo',
    'Gitoki',
    'Kabarore',
    'Kageyo',
    'Kiramuruzi',
    'Kiziguro',
    'Muhura',
    'Murambi',
    'Ngarama',
    'Nyagihanga',
    'Remera',
    'Rugarama',
    'Rwimbogo',
  ],
  'EAS-KAY': [
    'Gahini',
    'Kabare',
    'Kabarondo',
    'Mukarange',
    'Murama',
    'Murundi',
    'Mwiri',
    'Ndego',
    'Nyamirama',
    'Rwinkwavu',
    'Rurenge',
    'Kazo',
    'Ruramira',
  ],
  'EAS-KIR': [
    'Gahara',
    'Gatore',
    'Kigarama',
    'Kigina',
    'Kirehe',
    'Mahama',
    'Mpanga',
    'Musaza',
    'Mushikiri',
    'Nasho',
    'Nyamugari',
    'Nyarubuye',
  ],
  'EAS-NGO': [
    'Gasanza',
    'Karembo',
    'Kazo',
    'Kibungo',
    'Muhazi',
    'Mugesera',
    'Murama',
    'Mutenderi',
    'Remera',
    'Rukira',
    'Rukumberi',
    'Rurenge',
    'Sake',
    'Zaza',
  ],
  'EAS-NYA': [
    'Gatunda',
    'Karama',
    'Karangazi',
    'Katabagemu',
    'Katranzige',
    'Kibali',
    'Kiyombe',
    'Matimba',
    'Mimuli',
    'Mukama',
    'Musheri',
    'Nyagatare',
    'Rukomo',
    'Rwempasha',
    'Rwimiyaga',
    'Tabagwe',
  ],
  'EAS-RWA': [
    'Fumbwe',
    'Gahengeli',
    'Gishari',
    'Karenge',
    'Kigabiro',
    'Muhazi',
    'Munyaga',
    'Munyiginya',
    'Musha',
    'Muyumbu',
    'Mwulire',
    'Nyakaliro',
    'Nzige',
    'Rubona',
  ],
  // Western Province
  'WES-KAR': [
    'Bwishyura',
    'Gashari',
    'Gishyita',
    'Gitesi',
    'Mubuga',
    'Murambi',
    'Murundi',
    'Mutuntu',
    'Rubengera',
    'Rugabano',
    'Ruganda',
    'Rwankuba',
    'Twumba',
  ],
  'WES-NGO': [
    'Bwira',
    'Gatumba',
    'Hindiro',
    'Kabaya',
    'Kageyo',
    'Kavumu',
    'Matyazo',
    'Muhanda',
    'Muhororo',
    'Ndaro',
    'Ngororero',
    'Nyange',
    'Sovu',
  ],
  'WES-NYB': [
    'Bigogwe',
    'Jenda',
    'Jomba',
    'Kabatwa',
    'Karago',
    'Kintobo',
    'Mukamira',
    'Muringa',
    'Rambura',
    'Rugera',
    'Rurembo',
    'Shyira',
  ],
  'WES-NYM': [
    'Bushekeri',
    'Bushenge',
    'Cyato',
    'Gihombo',
    'Kagano',
    'Kanjongo',
    'Karambi',
    'Karengera',
    'Kirimbi',
    'Macuba',
    'Mahembe',
    'Nyabitekeri',
    'Rangiro',
    'Ruharambuga',
    'Shangi',
  ],
  'WES-RUB': [
    'Bugeshi',
    'Busasamana',
    'Cyanzarwe',
    'Gihuta',
    'Gisenyi',
    'Kanama',
    'Kanzenze',
    'Mudende',
    'Nyamyumba',
    'Nyundo',
    'Rubavu',
    'Rugerero',
  ],
  'WES-RUS': [
    'Bugarama',
    'Butare',
    'Bweyeye',
    'Gashonga',
    'Giheke',
    'Gihundwe',
    'Gikundamvura',
    'Gitambi',
    'Kamembe',
    'Muganza',
    'Mururu',
    'Nkungu',
    'Nyakarenzo',
    'Nzahaha',
    'Rwimbogo',
  ],
  'WES-RUT': [
    'Boneza',
    'Gihango',
    'Kigeyo',
    'Kivumu',
    'Manihira',
    'Mukura',
    'Murunda',
    'Musasa',
    'Mushonyi',
    'Mushubati',
    'Nyabirasi',
    'Ruhango',
    'Rusebeya',
  ],
};

export async function seedSectors(dataSource: DataSource): Promise<void> {
  let inserted = 0;
  let skipped = 0;

  for (const [districtCode, sectorNames] of Object.entries(SECTORS)) {
    const districtRows = await dataSource.query(`SELECT id FROM districts WHERE code = $1`, [
      districtCode,
    ]);
    if (districtRows.length === 0) {
      // eslint-disable-next-line no-console
      console.warn(`[Seed] District code "${districtCode}" not found — skipping its sectors.`);
      continue;
    }
    const districtId: string = districtRows[0].id;

    for (const name of sectorNames) {
      const existing = await dataSource.query(
        `SELECT id FROM sectors WHERE name = $1 AND district_id = $2`,
        [name, districtId],
      );
      if (existing.length > 0) {
        skipped++;
        continue;
      }
      await dataSource.query(`INSERT INTO sectors (name, district_id) VALUES ($1, $2)`, [
        name,
        districtId,
      ]);
      inserted++;
    }
  }

  // eslint-disable-next-line no-console
  console.log(`[Seed] Sectors: ${inserted} inserted, ${skipped} already existed.`);
}
