export enum ErrorCode {
  // Auth
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_PHONE_EXISTS = 'AUTH_PHONE_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  AUTH_PHONE_ALREADY_VERIFIED = 'AUTH_PHONE_ALREADY_VERIFIED',
  AUTH_OTP_NOT_FOUND = 'AUTH_OTP_NOT_FOUND',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_MAX_ATTEMPTS = 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED = 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_MFA_ALREADY_ENABLED = 'AUTH_MFA_ALREADY_ENABLED',
  AUTH_MFA_SETUP_NOT_INITIATED = 'AUTH_MFA_SETUP_NOT_INITIATED',
  AUTH_MFA_INVALID_CODE = 'AUTH_MFA_INVALID_CODE',

  // Two-Factor Authentication (SMS OTP)
  AUTH_2FA_ALREADY_ENABLED = 'AUTH_2FA_ALREADY_ENABLED',
  AUTH_2FA_NOT_ENABLED = 'AUTH_2FA_NOT_ENABLED',
  AUTH_2FA_SETUP_NOT_INITIATED = 'AUTH_2FA_SETUP_NOT_INITIATED',
  AUTH_2FA_INVALID_CODE = 'AUTH_2FA_INVALID_CODE',
  AUTH_2FA_TEMP_TOKEN_INVALID = 'AUTH_2FA_TEMP_TOKEN_INVALID',
  AUTH_2FA_OTP_RATE_LIMITED = 'AUTH_2FA_OTP_RATE_LIMITED',

  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
